### ISSUE TITLE
Updated instructions

### ISSUE THREAD

**Issue by ThatOneShortGuy** [ArcanePigeon/QuickStack#1]
I was reading on the curseforge site trying to find what the keybinds were. I was not able to find them there. I came here to look at the readme, but couldn't find anything. On my own, I discovered that "v" was quickstack, but that's all I was able to find. Also, does this only work in single player worlds? or what about multiplayer worlds?

**Comment by ArcanePigeon** [comment]
This works on servers as long as it is installed on the server too. You can find the keybindings in the normal keybindings menu.
